version: '3.1'

services:

db:
  image: mariadb:10.6
  container_name: my-mariadb
  restart: always
  environment:
    MARIADB_USER: whaticket
    MARIADB_PASSWORD: whaticket
    MARIADB_ROOT_PASSWORD: whaticket_root
  volumes:
    - mariadb_volume:/var/lib/mysql/data/
  ports:
    - 127.0.0.1:3306:3306

volumes:
  mariadb_volume: